### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by jimmyfyx** [NagabhushanSN95/DeCOMPnet#8]
Hi,

I have a few questions regarding the training part, especially the data format for training.

- In `src/flow_estimation/data_loaders/VeedDynamic01.py`, within the `load_training_data` function, what is the purpose of the block from line 64 to 70? Could you clarify its use a little bit?
- From the dataloader it seems that each piece of training data only contains a patch of the full-size image. If we only have one patch available each time, how can we estimate the flow of the whole image? Is this a intended design for the model with the backbone as  PWC-Net? If there is somewhere I can get more information on this can you point me to that? Thanks!

**Comment by NagabhushanSN95** [comment]
1. As I mentioned [in this issue](https://github.com/NagabhushanSN95/DeCOMPnet/issues/6#issuecomment-1802333777), 

> We train the flow estimator to predict the object motion from `f_n` to `f_{n-2}` as well as `f_n` to `f_{n+1}` (by picking one of them randomly).

[Lines 64--75](https://github.com/NagabhushanSN95/DeCOMPnet/blob/main/src/flow_estimation/data_loaders/VeedDynamic01.py#L64-L75) essentially do that - pick one of them at random.

2. PWC-Net/ARFlow are fully convolutional - i.e. the resolution of input images can vary between train and test time, and it works fine. Due to GPU memory constraints, we train on patches and not on full images. Obviously, if you can train on full images, that's best. The model can learn better. However, while training on patches, the `patch_size` is important. `patch_size` should be bigger than the motion expected in the dataset. In other words, the cropped patches should have matching moving objects for the flow estimator to train. We choose the `patch_size` by visual inspection.

**Comment by jimmyfyx** [comment]
Thanks for the answer! Ah I see, sorry I missed your previous answer. But in the training data, shouldn't we need the flow from `f_n` to `f_{n-2}` and `f_n` to `f_{n+1}` at the same time? Why we need to pick one of them at random?

**Comment by NagabhushanSN95** [comment]
Flow estimator is trained separately, independent of what our entire framework is doing. The goal of this training is to learn flow estimation between MPIs. So, it doesn't matter which frames you estimate the flow between. The only thing that matters is that camera motion should be nullified between the frames.
